title: JAYESH.G.NAKASKAR # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br> HELLO WORLD ! 

I'm Jayesh Nakaskar a born programmer and software engineer working with it throughout recent years. I have self-picked up programming dialects like C, C++, C#, JAVA, PYTHON, and that's just the beginning. 

I explicitly like playing with logic (i.e Programming). I am even capable in numerous different fields of tech like android development, blockchain development, Linux Expert, and so on.

I'm fluent in Unity and have been working with it for around 2+ years now. On my journey until now, I have figured out how to make attractive games along with making around a dozen games yet. I can even utilize Unreal Engine modestly alongside having ample experience in it as well. 

On a side note, I have had a vision of incorporating Crypto and Gaming from past years although I am diving into it for quite a while already. <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
 
